# fly.toml app configuration file generated for capricamc on 2024-05-19T11:00:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'capricamc'
primary_region = 'dfw'
kill_signal = 'SIGTERM'
kill_timeout = '2m0s'

[build]
  image = 'itzg/minecraft-server:latest'

[deploy]
  wait_timeout = '5m0s'

[env]
  AUTOSTOP_PKILL_USE_SUDO = 'TRUE'
  AUTOSTOP_TIMEOUT_EST = '300'
  AUTOSTOP_TIMEOUT_INIT = '300'
  ENABLE_AUTOSTOP = 'TRUE'
  EULA = 'TRUE'
  EXISTING_WHITELIST_FILE = 'SYNCHRONIZE'
  MEMORY = '3G'
  MEMORY_MAX = '5G'
  MOTD = 'Hi Emma!'
  OPS = 'DarlesBarkley'
  PLUGINS = 'https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot,https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot'
  TYPE = 'PAPER'
  WHITELIST = 'DarlesBarkley'

[[mounts]]
  source = 'minecraft_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 25565
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 25565

[experimental]
  allowed_public_ports = [19132, 19133]
  auto_rollback = false

[[services]]
  internal_port = 19132
  protocol = "udp"

  [[services.ports]]
    port = 19132

[[services]]
  internal_port = 19133
  protocol = "udp"

  [[services.ports]]
    port = 19133

[checks]
  [checks.minecraft_server_tcp_check]
    port = 25565
    type = 'tcp'
    interval = '30s'
    timeout = '20s'
    grace_period = '30s'

[[vm]]
  memory = '6gb'
  cpu_kind = 'shared'
  cpus = 4